name: Publish

on: [push, pull_request]

jobs:
  Build-and-Publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Generate Packages
      run: dotnet pack -c Release -o out
    - name: Publish to NuGet
      run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish to GitHub
      run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.GH_PACKAGE_KEY}} --source https://nuget.pkg.github.com/Kontore/index.json --skip-duplicate